export const specialsLabels = {
  en: {
    title: "JOKO Specials",
    intro: "Prepare today’s surplus, special prices and pickup window.",
    stage:
      "Preparation only. Publishing, customer payments and LINE sending will be enabled after the checkout integration is validated.",
    newBatch: "New batch",
    refresh: "Refresh",
    save: "Save draft",
    product: "Product",
    price: "Special price (฿)",
    limit: "Maximum per customer (optional)",
    add: "Save offer",
    own: "I confirm this product is made by JOKO.",
    available: "Available",
    held: "Held",
    sold: "Committed",
    allocated: "Allocated",
    prepare: "Prepare batch",
    close: "Close batch",
    cancel: "Cancel batch",
    preview: "Customer preview",
    history: "Audit history",
    transfer: "Transfer stock",
    source: "Source / destination reference",
    reason: "Reason",
    quantity: "Physical units",
    isolated:
      "I have physically isolated these units and removed them from all other selling channels.",
    quality:
      "These units have no existing customer allocation and meet our quality standards.",
    titleField: "Batch title",
    location: "Pickup location",
    start: "Sales start",
    end: "Sales end",
    pickupStart: "Pickup start",
    pickupEnd: "Pickup end",
    notes: "Internal notes",
    in: "Transfer in",
    out: "Release available stock",
    empty: "No batches yet. Create today’s first draft.",
    times:
      "All times are Bangkok time. Allow 5 minutes for payment and 15 minutes between sales end and pickup end.",
    retry: "Retry the same operation",
    uncertain:
      "This operation has an unresolved result. Retry it before making another change; the original operation key prevents duplicate transfers.",
    saved: "Saved.",
    draftOnly:
      "Prepared batches are locked. Close or cancel, then record where any remaining stock goes.",
    today: "Pickup today only",
    leftover:
      "Closing does not move physical stock. Record a release for every unsold unit.",
    edit: "Edit offer",
    enabled: "Offer enabled",
    sourceHint:
      "Manual counted surplus only. Scheduled product capacity is not deducted.",
    noEvents: "No audit events yet.",
  },
  th: {
    title: "JOKO Specials",
    intro: "เตรียมสินค้าคงเหลือ ราคาพิเศษ และเวลารับสินค้าของวันนี้",
    stage:
      "ขั้นเตรียมการเท่านั้น จะเปิดขาย ชำระเงิน และส่ง LINE หลังตรวจสอบระบบชำระเงินแล้ว",
    newBatch: "รอบใหม่",
    refresh: "รีเฟรช",
    save: "บันทึกร่าง",
    product: "สินค้า",
    price: "ราคาพิเศษ (฿)",
    limit: "จำนวนสูงสุดต่อลูกค้า (ไม่บังคับ)",
    add: "บันทึกข้อเสนอ",
    own: "ยืนยันว่าสินค้านี้ผลิตโดย JOKO",
    available: "พร้อมขาย",
    held: "จองชั่วคราว",
    sold: "จัดสรรแล้ว",
    allocated: "จัดสรรทั้งหมด",
    prepare: "เตรียมรอบขาย",
    close: "ปิดรอบ",
    cancel: "ยกเลิกรอบ",
    preview: "ตัวอย่างหน้าลูกค้า",
    history: "ประวัติการดำเนินการ",
    transfer: "โอนสต็อก",
    source: "แหล่งที่มา / ปลายทาง",
    reason: "เหตุผล",
    quantity: "จำนวนชิ้นจริง",
    isolated: "แยกสินค้าจริงแล้วและนำออกจากทุกช่องทางขายอื่นแล้ว",
    quality: "สินค้ายังไม่จัดสรรให้ลูกค้าและผ่านมาตรฐานคุณภาพ",
    titleField: "ชื่อรอบขาย",
    location: "จุดรับสินค้า",
    start: "เริ่มขาย",
    end: "สิ้นสุดการขาย",
    pickupStart: "เริ่มรับสินค้า",
    pickupEnd: "สิ้นสุดการรับสินค้า",
    notes: "บันทึกภายใน",
    in: "โอนเข้า",
    out: "นำสต็อกพร้อมขายออก",
    empty: "ยังไม่มีรอบขาย สร้างร่างสำหรับวันนี้",
    times:
      "ทุกเวลาเป็นเวลากรุงเทพฯ เผื่อชำระเงิน 5 นาที และเผื่อรับสินค้า 15 นาทีหลังสิ้นสุดการขาย",
    retry: "ลองดำเนินการเดิมอีกครั้ง",
    uncertain:
      "ผลการดำเนินการยังไม่ชัดเจน ลองรายการเดิมอีกครั้งก่อนทำรายการใหม่ เพื่อป้องกันการโอนซ้ำ",
    saved: "บันทึกแล้ว",
    draftOnly:
      "รอบที่เตรียมแล้วถูกล็อก ปิดหรือยกเลิก แล้วบันทึกปลายทางของสต็อกที่เหลือ",
    today: "รับสินค้าวันนี้เท่านั้น",
    leftover: "การปิดรอบไม่ย้ายสินค้าจริง ต้องบันทึกการนำสินค้าที่เหลือออก",
    edit: "แก้ไขข้อเสนอ",
    enabled: "เปิดใช้ข้อเสนอ",
    sourceHint: "ใช้สินค้าคงเหลือที่นับจริงเท่านั้น ไม่หักกำลังการผลิตตามกำหนด",
    noEvents: "ยังไม่มีประวัติ",
  },
  zh: {
    title: "JOKO Specials",
    intro: "准备今日余量、特价和取货时间。",
    stage: "目前仅供准备。结账验证完成后才会开启发布、付款和 LINE 发送。",
    newBatch: "新批次",
    refresh: "刷新",
    save: "保存草稿",
    product: "商品",
    price: "特价 (฿)",
    limit: "每位顾客上限（可选）",
    add: "保存优惠",
    own: "我确认此商品由 JOKO 制作。",
    available: "可售",
    held: "暂留",
    sold: "已分配",
    allocated: "总分配",
    prepare: "准备批次",
    close: "关闭批次",
    cancel: "取消批次",
    preview: "顾客预览",
    history: "操作记录",
    transfer: "转移库存",
    source: "来源 / 去向记录",
    reason: "原因",
    quantity: "实际件数",
    isolated: "我已将这些商品实物隔离，并从所有其他销售渠道移除。",
    quality: "这些商品尚未分配给顾客，且符合质量标准。",
    titleField: "批次名称",
    location: "取货地点",
    start: "销售开始",
    end: "销售结束",
    pickupStart: "取货开始",
    pickupEnd: "取货结束",
    notes: "内部备注",
    in: "转入",
    out: "释放可售库存",
    empty: "暂无批次。请创建今日草稿。",
    times:
      "所有时间均为曼谷时间。需预留 5 分钟付款，并在销售结束后预留 15 分钟取货。",
    retry: "重试同一操作",
    uncertain: "操作结果尚未明确。请先重试原操作；原操作编号可防止重复转移。",
    saved: "已保存。",
    draftOnly: "已准备的批次已锁定。关闭或取消后，请记录剩余库存去向。",
    today: "仅限今日取货",
    leftover: "关闭不会移动实物。请逐一记录未售库存的去向。",
    edit: "编辑优惠",
    enabled: "启用优惠",
    sourceHint: "仅使用已清点的实物余量，不扣减计划产能。",
    noEvents: "暂无操作记录。",
  },
} as const;
