export const specialsCustomerCopy = {
  en: {
    eyebrow: 'Made by JOKO · Pick up today', heading: 'A little extra.', accent: 'A special price.',
    intro: 'Today’s small selection of JOKO bakery favourites, at a little less. Limited quantities, ready for same-day pickup.',
    pickup: 'Today’s pickup', closes: 'Checkout closes', timezone: 'Thailand time',
    rules: ['Made by JOKO', 'Same-day pickup only', 'Pay online to confirm', 'Limited quantities'],
    today: 'Today’s Specials', lasts: 'While they last', special: 'Special price', soldOut: 'Sold out', available: 'available',
    add: 'Add', remove: 'Remove one', quantity: 'Quantity', basket: 'Your Specials', emptyBasket: 'Choose something lovely from today’s selection.',
    total: 'Total', pay: 'Continue to payment', busy: 'Holding your selection…', retry: 'Retry pending checkout', signIn: 'Sign in to checkout',
    hold: 'Your selection is held for 15 minutes once checkout succeeds. Payment confirms your order.',
    browse: 'Browse today’s Specials', orders: 'My Orders', different: 'A different kind of bakery order.',
    separate: 'Specials are for pickup today at the location above. They have their own checkout; your regular pre-order basket stays separate.',
    noSpecials: 'No Specials available right now.', checkLater: 'Today’s selection is limited. Please check again later.', loading: 'Loading today’s Specials…',
    pending: 'A checkout request is awaiting confirmation. Retry your saved selection or check My Orders before creating another checkout.',
    maps: 'View pickup location', selected: 'selected', changed: 'Availability has changed. Adjust the highlighted quantities before continuing.',
  },
  th: {
    eyebrow: 'ทำโดย JOKO · รับสินค้าวันนี้', heading: 'ความอร่อยที่มีเพิ่ม', accent: 'ในราคาพิเศษ',
    intro: 'ขนมโปรดจาก JOKO ที่มีพร้อมวันนี้ ในราคาพิเศษ จำนวนจำกัด รับสินค้าได้ภายในวันนี้เท่านั้น',
    pickup: 'รับสินค้าวันนี้', closes: 'ปิดรับคำสั่งซื้อ', timezone: 'เวลาไทย',
    rules: ['ทำโดย JOKO', 'รับสินค้าวันนี้เท่านั้น', 'ชำระออนไลน์เพื่อยืนยัน', 'จำนวนจำกัด'],
    today: 'ราคาพิเศษวันนี้', lasts: 'จนกว่าสินค้าจะหมด', special: 'ราคาพิเศษ', soldOut: 'หมดแล้ว', available: 'ชิ้นพร้อมขาย',
    add: 'เพิ่ม', remove: 'ลดหนึ่งชิ้น', quantity: 'จำนวน', basket: 'รายการราคาพิเศษของคุณ', emptyBasket: 'เลือกขนมที่คุณชอบจากรายการวันนี้',
    total: 'รวม', pay: 'ดำเนินการชำระเงิน', busy: 'กำลังจองสินค้า…', retry: 'ลองยืนยันคำสั่งซื้ออีกครั้ง', signIn: 'เข้าสู่ระบบเพื่อสั่งซื้อ',
    hold: 'สินค้าได้รับการจองไว้ 15 นาทีเมื่อสร้างคำสั่งซื้อสำเร็จ ชำระเงินเพื่อยืนยันคำสั่งซื้อ',
    browse: 'ดูรายการราคาพิเศษวันนี้', orders: 'คำสั่งซื้อของฉัน', different: 'คำสั่งซื้อสำหรับวันนี้โดยเฉพาะ',
    separate: 'รับสินค้าราคาพิเศษวันนี้ ณ จุดรับสินค้าที่ระบุ มีการชำระเงินแยกจากตะกร้าพรีออเดอร์ปกติของคุณ',
    noSpecials: 'ยังไม่มีสินค้าราคาพิเศษในขณะนี้', checkLater: 'สินค้าวันนี้มีจำนวนจำกัด โปรดกลับมาตรวจสอบอีกครั้ง', loading: 'กำลังโหลดรายการวันนี้…',
    pending: 'คำสั่งซื้อกำลังรอการยืนยัน ลองยืนยันรายการเดิมหรือตรวจสอบคำสั่งซื้อของฉันก่อนสร้างคำสั่งซื้อใหม่',
    maps: 'ดูจุดรับสินค้า', selected: 'ชิ้นที่เลือก', changed: 'จำนวนสินค้ามีการเปลี่ยนแปลง โปรดปรับจำนวนที่ระบุก่อนดำเนินการต่อ',
  },
  zh: {
    eyebrow: 'JOKO 自制 · 今日取货', heading: '多一点美味。', accent: '特别的价格。',
    intro: '今日少量 JOKO 烘焙好物，优惠供应。数量有限，仅限当天取货。',
    pickup: '今日取货', closes: '结账截止', timezone: '泰国时间',
    rules: ['JOKO 自制', '仅限当天取货', '在线付款确认', '数量有限'],
    today: '今日特惠', lasts: '售完即止', special: '特惠价格', soldOut: '已售罄', available: '件可购买',
    add: '添加', remove: '减少一件', quantity: '数量', basket: '您的特惠商品', emptyBasket: '从今日精选中挑选您喜欢的美味。',
    total: '合计', pay: '继续付款', busy: '正在预留商品…', retry: '重试待确认订单', signIn: '登录后结账',
    hold: '结账成功后，商品为您预留 15 分钟。付款后订单确认。',
    browse: '浏览今日特惠', orders: '我的订单', different: '专为今天准备的订单。',
    separate: '特惠商品仅限今天在上述地点领取，单独结账；您的普通预订购物篮保持独立。',
    noSpecials: '目前暂无特惠商品。', checkLater: '今日数量有限，请稍后再来看看。', loading: '正在加载今日特惠…',
    pending: '订单正在等待确认。请重试已保存的选择或查看我的订单，然后再创建新订单。',
    maps: '查看取货地点', selected: '件已选择', changed: '库存已发生变化。请调整标出的数量后再继续。',
  },
} as const;
